---
title: Know Thyself
date: 2025-09-14 10:23:45
author: Apurva Nakade
categories: ['vipassana', 'meditation', 'mindfulness', 'retreat', 'goenka']
---

In summer of 2025 I attended a 10-day Vipassana course in [Delaware](https://pubbananda.dhamma.org/). In the moment, this was very difficult and painful. But looking back this was one of the most valuable experiences in my life.  This post is one of the many that contain my experiences and lessons from the course.

---

When you get to the center feeling lost and confounded, unsure as to whether this is a good way to spend your 10 days, you expect there to be friendly volunteers who will assuage your worries. Someone who will tell you that this is indeed the right decision. Now, you do meet a lot of nice people but mostly they tell you where the rooms are and what time you need to eat. Everything else they say you'll figure it out. 

Next day the wake-up bell rings at 4:30 am. It is the first day so you end up at the meditation hall a bit sleep deprived and unsure as to what to do. S.N. Goenka simply asks you to focus on your breath and nothing else. It is really frustrating. 

You do get a chance to meet the assistant teacher later in the day but by then you have already spent several hours with nobody but yourself, with nothing but your mind. Your back and your legs have started to hurt and there is no resolution coming forth. 

I learned a very valuable lesson from all of this minimal instruction, all this frustration. The reason I had been having so much difficulty sitting with myself is that I have never truly sat with yourself before. I have my phone and my computer and my friends and my work all to keep me from myself. Should you need instructions on what to do when you are alone? 

Being able to be with yourself and nothing else is the first step in the path towards knowing yourself. In the end, the path of vipassana is nothing more but an inward bound path towards inner knowledge. As Joseph Goldstein says, "the goal is to make your mind your friend."