---
title: Non-Profits
author: Apurva Nakade
date: 2025-05-13 10:43:08
---

My apartment complex in DC is having some landlord issues. [Our landlord](https://www.yelp.com/biz/tsintolas-realty-washington) is a shady, dishonest guy whose main skill is not getting sued. He will do the absolute least he can to avoid being held liable. This post is not about him, though. This post is about some awesome people in DC.

We are having some legal issues with the landlord, and one of our fellow tenants reached out to some DC non-profits called [Legal Aid DC](https://www.legalaiddc.org/) and [Housing Counseling Services](https://housingetc.org/). Some of their hardworking folks came to our apartment and talked to us about DC tenant laws, patiently answering all of our dumb questions. They spent their valuable time with us after a busy day and gave us the gift of time and knowledge -- all of this at no cost! By the end of our meeting, we all breathed a sigh of relief -- a big burden had been taken off our shoulders.

I was touched by their generosity, and it made me greatly appreciate the value of non-profits. It made me appreciate how much impact small acts of kindness can have. I hope to be able to support these organizations somehow, but more importantly, to spread their message and spirit.
