project:
  type: website
  output-dir: docs

website:
  title: "Second Drafts"
  navbar: true
  open-graph: true
  site-url: https://github.com/apurvanakade/second-drafts/
  repo-url: https://github.com/apurvanakade/second-drafts/
  search:
    type: overlay
    location: navbar
  

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css

output-dir: docs