project:
  type: website
  output-dir: docs

website:
  title: "Second Drafts"
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true
  page-footer: "Copyright 2025, Apurva Nakade" 
  site-url: https://github.com/apurvanakade/second-drafts/
  repo-url: https://github.com/apurvanakade/second-drafts/
  navbar:
    left:
      - text: Home
        href: https://apurvanakade.github.io/
      - text: Class Notes
        href: https://apurvanakade.github.io/notes.html
      - text: (Math) Blog
        href: index.qmd
      - text: CV 
        href: https://apurvanakade.github.io/CV.html
    right:
      - icon: github
        href: https://github.com/apurvanakade/
        aria-label: GitHub
  search:
    type: overlay
    location: navbar
  sidebar: 
    style: floating
    contents:
      - section: Maths
        contents:
          - maths/index.qmd
          - posts/maths/with-without-order.qmd
          - posts/maths/nth-fibonacci.qmd
          - posts/maths/bayes-theorem.qmd
          - posts/maths/sperners-lemma-geometric-proof.qmd
          - posts/maths/sperners-lemma-combinatorial-proof.qmd
          - posts/maths/sperners-lemma-statement.qmd
          - posts/maths/random-points-in-a-triangle.qmd
          - posts/maths/barycentric-coordinates.qmd
      - section: Scribbles
        contents:
          - scribbles/index.qmd
          - posts/scribbles/programming.qmd
          - posts/scribbles/architects-gardeners.qmd
          - posts/scribbles/remembering-learning.qmd
          - posts/scribbles/begin-again.qmd
  # comments:
  #   giscus:
  #     repo: "apurvanakade/giscus"

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css

execute:
  cache: true
  echo: false

jupyter: myenv

output-dir: docs
