project:
  type: website
  output-dir: docs

website:
  title: "Second Drafts"
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true
  page-footer: "Copyright 2025, Apurva Nakade" 
  site-url: https://github.com/apurvanakade/second-drafts/
  repo-url: https://github.com/apurvanakade/second-drafts/
  navbar:
    left:
      - text: Home
        href: https://apurvanakade.github.io/
      - text: Class Notes
        href: https://apurvanakade.github.io/notes.html
      - text: Second Drafts
        href: https://apurvanakade.github.io/second-drafts/
      - text: CV 
        href: https://apurvanakade.github.io/CV.html
    right:
      - icon: github
        href: https://github.com/apurvanakade/
        aria-label: GitHub
  search:
    type: overlay
    location: navbar
  # sidebar: 
  #   style: floating
  #   search: true
  #   contents: posts/

  

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css

output-dir: docs