---
title: Doing Hard Things
date: 2026-03-05 16:24:37
author: Apurva Nakade
categories: ['teaching', 'philosophy']
image: "../images/doing-hard-things-title.svg"
---

Casey Neistat has a couple of videos that I just love. In part, because I love running myself and I find it to be a very spiritual experience, but also because I love the message. I keep thinking about these videos because I think they contain a message that I wish I could convey to my students.

My courses tend to be quite hard. I don't try to make them intentionally hard, and I don't believe in learning through suffering. But I do believe in learning through struggling. When you really try to learn something well, when you keep digging and keep digging, you will hit rock, but that doesn't mean you stop. If you want to get to the hidden treasure, you have to keep digging. And that's back-breaking work.

I used to worry about this. About making things too hard. But now I believe that if my courses are not hard, I'm actually robbing my students of the joy of accomplishing something difficult. Now I consider it my moral responsibility to make sure that students are going through the right kind of struggle that leaves them with a sense of pride and accomplishment. This requires a support system, a lot of scaffolding, a lot of intention and attention on my part. I do not always succeed in providing these, but I sincerely try.

That is what I want my courses to feel like to my students - I want them to feel challenged, but also supported. I want to help them to get to the finish line, not whimpering and crawling, but with great cheers and applause, to feel the joy of having accomplished something truly difficult.

<iframe width="560" height="315" src="https://www.youtube.com/embed/9IiTdSnmS7E?si=11_3tlB_6Cq60x_U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


<iframe width="560" height="315" src="https://www.youtube.com/embed/StMltAX0mp0?si=P7B_MMe998MeoqTA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


---