---
title: Learning is Remembering
date: 2025-06-19 21:44:00
author: Apurva Nakade
categories: ['philosophy', 'teaching', 'buddhism', 'mindfulness', 'greeks']
---

"Mindfulness" is one of the most hyped words today. 
It has been corrupted, translated, and assimilated in the Western zeigeist. 
Which is a good thing overall, but words lose some of their meaning and intention when we try to translate them.

I don't know the reason this gets translated to mindfulness - what is the history of this word? When did this first appear in the English language?

The word for mindfulness in Pali is Sati and in Sanskrit it's Smruti. 
I grew up speaking Marathi and Hindi which are very close to Sanskrit and in them Smruti means memory. 
This word is usually used in the context of the Vedas which in their original form were transmitted orally.
You often see in Buddhism that the Buddha took many abstract concepts from Hinduism and modified their meaning. (We'll never know how much he was responsible for this as his words were only passed down orally and only put into text much much later.)

He changed the meaning of the word Smruti from memory i.e. remembering the past to "remembering the present". Mindfulness, in the Buddhist texts, is the practice of REMEMBERING the present moment, your Buddha nature, the wisdom that is already present inside you.

It is funny how the same concepts reappear in different forms in different contemplative traditions around the world. Greek philosophy has the concept of "anamnesis" which roughly means that "learning is remembering," that the wisdom is already inside you are trying to discover it, bring it forth, clean the looking glass so to speak. 

Fast forward to today, and today mathematicians speak of "discovering theorems". We imagine that there is a world of mathematics out there and we are explorers searching for new truths. But where is the out there? I think the out there is inside you. You discover theorems by searching your own mind. 

This has affected a lot of how I think about teaching. I now take the idea seriously that my job is to help students discover their inner wisdom. The cliche of unlocking your inner potential might be quite literally true.  