---
title: Pythagoras using Hilbert 90
date: 2024-06-08 12:33:01
categories:
  - abstract algebra
image: "../../maths/images/pythagoras-hilbert90-equation.svg"
author: Apurva Nakade
---

Dummit and Foote has a fun way of classifying Pythagorean triples. It is a classic fact that if $(a, b, c)$ is a reduced Pythagorean triple then there exists integers $m, n$ such that 

$$ 
\begin{align*}
  a &= m^2 - n^2, \\
  b &= 2mn, \\
  c &= m^2 + n^2.
\end{align*}
$$

To prove this using Hilbert's 90, first we change the problem to rational numbers i.e.
let $a, b\in \mathbb{Q}$ be such that $a^2 + b^2 = 1$. We want to show that there exists $m, n \in \mathbb{Q}$ such that
$$
\begin{align*}
  a &= \frac{m^2 - n^2}{m^2 + n^2}, \\
  b &= \frac{2mn}{m^2 + n^2}.
\end{align*}
$$

Consider the cyclic extensions $\mathbb{Q}(i)/\mathbb{Q}$.
The norm map is given by $N(a + bi) = a^2 + b^2$.
So, $a ^ 2 + b ^ 2 = 1$ implies that $N(a + bi) = 1$.
The Galois group $\mathbb{Z}/2\mathbb{Z}$ is generated by complex conjugation $\sigma : i \mapsto -i$.
So by Hilbert's 90, $$ a + bi = \frac{m + ni}{\sigma(m + ni)} = \frac{m + ni}{m - ni} $$ for some $m, n \in \mathbb{Q}$.
We can clear out the denominators to assume that $m, n \in \mathbb{Z}$ so that 
$$ 
a + bi = \frac{m + ni}{m - ni} = \frac{m^2 - n^2 + 2mni}{m^2 + n^2} = \frac{m^2 - n^2}{m^2 + n^2} + \frac{2mn}{m^2 + n^2}i
$$
as desired.

Now my math history isn't the best, but I have a feeling that this isn't how Pythagoras originally proved his theorem.
