---
title: Begin Again
author: Apurva Nakade
date: 2025-05-03 09:11:32
categories: []
# draft: true
---

I opened this page with a clear idea of what I wanted to write. I've now spent the last half an hour updating quarto, creating a new github repository, fixing a git merge issue on the old repository, figuring out how to render drafts... this was a mistake. When I have something to write, I need to get the words out as soon as possible without worrying about where are going to go. 

---

One of the protagonist in [1Q84](https://www.goodreads.com/book/show/10357575-1q84), Tengo, is a writer. He teaches math at cram schools to make a living but his real passion is writing. At some point in his life he as to decide between writing and math, and he decides to write. 

Tengo is my alter-ego from a different dimension - funny that the book itself is about different dimensions. 
He chose writing where as I chose math. Thankfully math pays so I do not have to teach writing for a living. 

I've always loved writing. I have had several blogs representing different phrases of my life, each reflective of what I was going through at the time. I haven't blogged in the past few years.

- I wanted to focus more on math writing and my work.
- Do people write any more? Isn't this the age of videos?
- Why write a blog at all that nobody reads?
- ... so many excuses.

Recently I started reading [The Artist's Way](https://www.goodreads.com/book/show/615570.The_Artist_s_Way) and it inspired me to write again. I sometimes get stuck in logic and rationalizing and trying to find reasons to do something. But really, I just enjoy putting thoughts into words, and that is reason enough. I heard Neil Gaiman talk about how he likes to write with a fountain pen. And I do too, I find it magical to see words appear on paper. But, I write much slower on paper than I can think. And I move around a lot so I do not have the luxury of carrying ink cartridges with me. For me, writing here is the equivalent of writing with a fountain pen. Just watching words magically appear on the screen out of nowhere.

I'm calling this journal Second Drafts as that's what it's going to be. Nothing polished or well-thought but not stream-of-conscious either. I hope to write what comes to mind and then do one scan to clean it up. As Sam Harris says, it's never late to begin again.