---
title: On Camping
author: Apurva Nakade
date: 2025-05-03 09:11:32
categories: []
draft: true
---

I was camping last week in the Smokies. For four days, my life was reduced to the bare minimum - 

- Wake up when it got bright (no alarms, yay!). 
- Start a camp fire; eat oatmeal and fruits; drink coffee. 
- Drive to various trails and hike all day.
- Back to the campsite; start a camp fire; cook and eat dinner; clean up.
- Write in my journal; read [Siddhartha](https://www.goodreads.com/book/show/52036.Siddhartha); go to bed. 

That is not to say that things were smooth sailing. I ran into many difficulties, some more dire than others. For some I was well-prepared and for some I had to improvise. Some I dealt with successfully and some were a massive failure -- my personal favorite being that now I'm an expert at lighting a camp fire (or so I think). Some days I slept fitfully, and some days sound as a child. I went through a whole array of emotions - happy, ecstatic, bored, in pain, tired, but never sad or depressed. 

There is a great joy in the simple life, in having fewer choices, in solving problems smartly with few resources, in slowing down and contemplating life. 

